version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: globalchat_db
    environment:
      POSTGRES_USER: globalchat_user
      POSTGRES_PASSWORD: globalchat_password
      POSTGRES_DB: globalchat_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: